import { cssVarName, type FileIR } from "../../ir/ir.js";
import {
  baseClass,
  compoundClass,
  containerVariantClass,
  responsiveVariantClass,
  variantClass,
} from "../../ir/names.js";

const HEADER = "// Generated by @arviahq/compiler - do not edit.";

const HELPER = `const _isObj = (v) => v != null && typeof v === "object";
const _resolveStatic = (v, fallback) => (_isObj(v) ? (v.initial ?? fallback) : (v ?? fallback));

const _applyVariant = (c, variants, respClasses, cqClasses, v, raw, defaultVal, s) => {
  if (_isObj(raw)) {
    const initial = raw.initial ?? defaultVal;
    if (initial != null && variants[v] && variants[v][initial] && variants[v][initial][s]) {
      c += (c ? " " : "") + variants[v][initial][s];
    }
    for (const key in raw) {
      if (key === "initial") continue;
      const val = raw[key];
      const add = key.startsWith("$")
        ? (cqClasses[key.slice(1)] && cqClasses[key.slice(1)][v] && cqClasses[key.slice(1)][v][val]
            ? cqClasses[key.slice(1)][v][val][s]
            : undefined)
        : (respClasses[key] && respClasses[key][v] && respClasses[key][v][val]
            ? respClasses[key][v][val][s]
            : undefined);
      if (add) c += (c ? " " : "") + add;
    }
  } else {
    const val = raw;
    const add = val != null && variants[v][val] ? variants[v][val][s] : undefined;
    if (add) c += (c ? " " : "") + add;
  }
  return c;
};

const _h = (base, variants, compounds, defaults, responsive, respClasses, containers, cqClasses, slots, props) => {
  const out = {};
  for (const s of slots) {
    let c = base[s] || "";
    for (const v in variants) {
      const raw = props && props[v] !== undefined ? props[v] : defaults[v];
      c = _applyVariant(c, variants, respClasses, cqClasses, v, raw, defaults[v], s);
    }
    for (const [bp, overrides] of responsive) {
      for (const v in overrides) {
        if (props && props[v] !== undefined) continue;
        const val = overrides[v];
        const add = respClasses[bp] && respClasses[bp][v] && respClasses[bp][v][val]
          ? respClasses[bp][v][val][s]
          : undefined;
        if (add) c += (c ? " " : "") + add;
      }
    }
    for (const [cq, overrides] of containers) {
      for (const v in overrides) {
        if (props && props[v] !== undefined) continue;
        const val = overrides[v];
        const add = cqClasses[cq] && cqClasses[cq][v] && cqClasses[cq][v][val]
          ? cqClasses[cq][v][val][s]
          : undefined;
        if (add) c += (c ? " " : "") + add;
      }
    }
    for (const [match, cls] of compounds) {
      let ok = true;
      for (const v in match) {
        if (_resolveStatic((props && props[v]) ?? defaults[v], defaults[v]) !== match[v]) {
          ok = false;
          break;
        }
      }
      if (ok && cls[s]) c += (c ? " " : "") + cls[s];
    }
    out[s] = c;
  }
  return out;
};`;

/** Runtime values for the `tokens` export: `var()` references for moded
 *  themes (the custom properties carry the values), resolved literals for
 *  single-mode themes (no custom properties are emitted). */
export function buildTokensObject(ir: FileIR): Record<string, Record<string, string>> {
  const tokens: Record<string, Record<string, string>> = {};
  for (const v of ir.themeVars) {
    (tokens[v.group] ??= {})[v.name] = ir.themeModes
      ? `var(${cssVarName(v.group, v.name)})`
      : (v.byMode["default"] ?? "");
  }
  return tokens;
}

export function emitJs(ir: FileIR): string {
  if (ir.components.length === 0 && ir.styles.length === 0 && ir.themeVars.length === 0) {
    return `${HEADER}\nexport {};\n`;
  }

  const parts: string[] = ir.components.length > 0 ? [HEADER, HELPER] : [HEADER];

  for (const c of ir.components) {
    const base: Record<string, string> = {};
    for (const slot of c.slotNames) base[slot] = baseClass(c, slot);

    const variants: Record<string, Record<string, Record<string, string>>> = {};
    for (const variant of c.variants) {
      const values: Record<string, Record<string, string>> = {};
      for (const value of variant.values) {
        const slots: Record<string, string> = {};
        for (const slot of Object.keys(value.slots)) {
          slots[slot] = variantClass(c, variant.name, value.name, slot);
        }
        if (Object.keys(slots).length > 0) values[value.name] = slots;
      }
      variants[variant.name] = values;
    }

    const respClasses: Record<string, Record<string, Record<string, Record<string, string>>>> = {};
    for (const resp of c.responsive) {
      const bpMap: Record<string, Record<string, Record<string, string>>> = {};
      for (const [variantName, valueName] of Object.entries(resp.variants)) {
        const variant = c.variants.find((v) => v.name === variantName);
        const value = variant?.values.find((v) => v.name === valueName);
        if (!value) continue;
        const slots: Record<string, string> = {};
        for (const slot of Object.keys(value.slots)) {
          slots[slot] = responsiveVariantClass(c, variantName, valueName, resp.breakpoint, slot);
        }
        (bpMap[variantName] ??= {})[valueName] = slots;
      }
      respClasses[resp.breakpoint] = bpMap;
    }

    const cqClasses: Record<string, Record<string, Record<string, Record<string, string>>>> = {};
    for (const cq of c.containers) {
      const cqMap: Record<string, Record<string, Record<string, string>>> = {};
      for (const [variantName, valueName] of Object.entries(cq.variants)) {
        const variant = c.variants.find((v) => v.name === variantName);
        const value = variant?.values.find((v) => v.name === valueName);
        if (!value) continue;
        const slots: Record<string, string> = {};
        for (const slot of Object.keys(value.slots)) {
          slots[slot] = containerVariantClass(c, variantName, valueName, cq.container, slot);
        }
        (cqMap[variantName] ??= {})[valueName] = slots;
      }
      cqClasses[cq.container] = cqMap;
    }

    const compounds: [Record<string, string>, Record<string, string>][] = [];
    for (const compound of c.compounds) {
      const slots: Record<string, string> = {};
      for (const slot of Object.keys(compound.slots)) {
        slots[slot] = compoundClass(c, compound.match, slot);
      }
      if (Object.keys(slots).length > 0) {
        compounds.push([Object.fromEntries(compound.match), slots]);
      }
    }

    const responsive: [string, Record<string, string>][] = c.responsive.map((r) => [
      r.breakpoint,
      r.variants,
    ]);
    const containers: [string, Record<string, string>][] = c.containers.map((r) => [
      r.container,
      r.variants,
    ]);

    parts.push(
      `const ${c.name}_base = ${JSON.stringify(base, null, 2)};`,
      `const ${c.name}_variants = ${JSON.stringify(variants, null, 2)};`,
      `const ${c.name}_compounds = ${JSON.stringify(compounds, null, 2)};`,
      `const ${c.name}_defaults = ${JSON.stringify(c.defaults, null, 2)};`,
      `const ${c.name}_responsive = ${JSON.stringify(responsive, null, 2)};`,
      `const ${c.name}_respClasses = ${JSON.stringify(respClasses, null, 2)};`,
      `const ${c.name}_containers = ${JSON.stringify(containers, null, 2)};`,
      `const ${c.name}_cqClasses = ${JSON.stringify(cqClasses, null, 2)};`,
      `export function ${c.name}(props) {\n  return _h(${c.name}_base, ${c.name}_variants, ${c.name}_compounds, ${c.name}_defaults, ${c.name}_responsive, ${c.name}_respClasses, ${c.name}_containers, ${c.name}_cqClasses, ${JSON.stringify(c.slotNames)}, props);\n}`,
    );
  }

  for (const s of ir.styles) {
    parts.push(`export const ${s.name} = ${JSON.stringify(s.className)};`);
  }

  if (ir.themeVars.length > 0) {
    parts.push(`export const tokens = ${JSON.stringify(buildTokensObject(ir), null, 2)};`);
  }

  return parts.join("\n\n") + "\n";
}
