import fs from "node:fs";
import path from "node:path";
import { compile, type ThemeEnv } from "@arviahq/compiler";

export interface StorybookGenerateOptions {
  /** Directory to scan for .arv files. */
  cwd: string;
  /** Output directory for generated stories (relative to cwd). */
  outDir?: string;
  /** Theme file path (absolute or relative to cwd). */
  theme?: string;
}

export interface StorybookGenerateResult {
  files: string[];
  errors: string[];
}

interface ComponentMeta {
  name: string;
  slots: string[];
  variants: { name: string; values: string[] }[];
  defaults: Record<string, string>;
}

function relativeImport(from: string, to: string): string {
  let rel = path.relative(path.dirname(from), to).replace(/\\/g, "/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel.replace(/.arv$/, ".arv");
}

function emitStory(component: ComponentMeta, arviaPath: string, outPath: string): string {
  const importPath = relativeImport(outPath, arviaPath);
  const rootSlot = component.slots.includes("root") ? "root" : (component.slots[0] ?? "root");
  const labelSlot = component.slots.includes("label") ? "label" : rootSlot;

  const argTypes = component.variants
    .map((v) => {
      const options = v.values.map((val) => JSON.stringify(val)).join(", ");
      return `    ${JSON.stringify(v.name)}: { control: "select", options: [${options}] },`;
    })
    .join("\n");

  const defaultArgs = Object.entries(component.defaults)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");

  const variantMatrix = component.variants
    .map((variant) => {
      const stories = variant.values
        .map((value) => {
          const args = Object.entries(component.defaults)
            .map(([k, v]) => [k, k === variant.name ? value : v] as const)
            .map(([k, v]) => `      ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
            .join("\n");
          return `export const ${variant.name}_${value} = {
  args: {
${args}
  },
};`;
        })
        .join("\n\n");
      return stories;
    })
    .join("\n\n");

  return `// Generated by @arviahq/storybook — do not edit.
import { ${component.name} } from ${JSON.stringify(importPath)};

export default {
  title: "Arvia/${component.name}",
  render: (props: Record<string, unknown>) => {
    const styles = ${component.name}(props);
    return <div className={styles.${rootSlot}}><span className={styles.${labelSlot}}>${component.name}</span></div>;
  },
${argTypes ? `  argTypes: {\n${argTypes}\n  },` : ""}
};

export const Playground = {
  args: {
${defaultArgs || "    // no defaults"}
  },
};

${variantMatrix}
`;
}

export async function generateStorybook(
  options: StorybookGenerateOptions,
): Promise<StorybookGenerateResult> {
  const cwd = path.resolve(options.cwd);
  const outDir = path.resolve(cwd, options.outDir ?? "stories");
  const errors: string[] = [];
  const files: string[] = [];

  const arvFiles: string[] = [];
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".arv")) arvFiles.push(full);
    }
  };
  walk(cwd);

  const themePath = options.theme
    ? path.resolve(options.theme)
    : arvFiles.find((f) => path.basename(f) === "theme.arv");

  let env: ThemeEnv | undefined;
  if (themePath && fs.existsSync(themePath)) {
    const themeResult = compile(fs.readFileSync(themePath, "utf8"), {
      filename: themePath,
      root: cwd,
    });
    for (const d of themeResult.diagnostics) {
      if (d.severity === "error") errors.push(`${themePath}: ${d.message}`);
    }
    env = themeResult.env;
  }

  fs.mkdirSync(outDir, { recursive: true });

  for (const arviaPath of arvFiles) {
    if (arviaPath === themePath) continue;
    const source = fs.readFileSync(arviaPath, "utf8");
    const result = compile(source, { filename: arviaPath, env, root: cwd });
    let fileFailed = false;
    for (const d of result.diagnostics) {
      if (d.severity === "error") {
        errors.push(`${arviaPath}: ${d.message}`);
        fileFailed = true;
      }
    }
    if (fileFailed) continue;

    for (const component of result.meta.components) {
      const base = path.basename(arviaPath, ".arv");
      const storyName = result.meta.components.length > 1 ? `${base}-${component.name}` : base;
      const outPath = path.join(outDir, `${storyName}.stories.tsx`);
      const content = emitStory(component, arviaPath, outPath);
      fs.writeFileSync(outPath, content);
      files.push(outPath);
    }
  }

  return { files, errors };
}
