import type { Span } from "../../diagnostics.js";
import type { ComponentIR, FileIR } from "../../ir/ir.js";

const HEADER = "// Generated by @arviahq/compiler - do not edit.";

const TS_IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const key = (name: string) => (TS_IDENT_RE.test(name) ? name : JSON.stringify(name));

const FN_PREFIX = "export declare function ";

export interface DtsAnchor {
  name: string;
  sourceStart: number;
  sourceLength: number;
  generatedStart: number;
  generatedLength: number;
}

function conditionalType(union: string, breakpoints: string[], containers: string[]): string {
  if (breakpoints.length === 0 && containers.length === 0) return union;
  const keys = [
    ...breakpoints.map((b) => `${key(b)}?: ${union};`),
    ...containers.map((c) => `${JSON.stringify(`$${c}`)}?: ${union};`),
  ].join(" ");
  return `${union} | { initial?: ${union}; ${keys} }`;
}

function variantConditionalType(
  union: string,
  variantName: string,
  component: ComponentIR,
): string {
  const breakpoints: string[] = [];
  const containers: string[] = [];
  for (const entry of component.responsive) {
    if (variantName in entry.variants) breakpoints.push(entry.breakpoint);
  }
  for (const entry of component.containers) {
    if (variantName in entry.variants) containers.push(entry.container);
  }
  return conditionalType(union, breakpoints, containers);
}

export function emitDts(ir: FileIR): string {
  return emitDtsWithAnchors(ir).code;
}

const CONST_PREFIX = "export declare const ";

export function emitDtsWithAnchors(ir: FileIR): { code: string; anchors: DtsAnchor[] } {
  if (ir.components.length === 0 && ir.styles.length === 0) {
    return { code: `${HEADER}\nexport {};\n`, anchors: [] };
  }

  const parts: string[] = [HEADER];
  const fnDecls: { partIndex: number; name: string; nameSpan: Span; prefixLength: number }[] = [];
  for (const c of ir.components) {
    const slotsType = `export type ${c.name}Slots = {\n${c.slotNames
      .map((slot) => `  ${key(slot)}: string;`)
      .join("\n")}\n};`;

    if (c.variants.length > 0) {
      const props = c.variants
        .map((variant) => {
          const union =
            variant.values.length > 0
              ? variant.values.map((value) => JSON.stringify(value.name)).join(" | ")
              : "never";
          const type = variantConditionalType(union, variant.name, c);
          return `  ${key(variant.name)}?: ${type};`;
        })
        .join("\n");
      parts.push(
        `export type ${c.name}Props = {\n${props}\n};`,
        slotsType,
        `${FN_PREFIX}${c.name}(props?: ${c.name}Props): ${c.name}Slots;`,
      );
    } else {
      parts.push(slotsType, `${FN_PREFIX}${c.name}(): ${c.name}Slots;`);
    }
    fnDecls.push({
      partIndex: parts.length - 1,
      name: c.name,
      nameSpan: c.nameSpan,
      prefixLength: FN_PREFIX.length,
    });
  }

  for (const s of ir.styles) {
    parts.push(`${CONST_PREFIX}${s.name}: string;`);
    fnDecls.push({
      partIndex: parts.length - 1,
      name: s.name,
      nameSpan: s.nameSpan,
      prefixLength: CONST_PREFIX.length,
    });
  }

  const code = parts.join("\n\n") + "\n";

  const partOffsets: number[] = [];
  let offset = 0;
  for (let i = 0; i < parts.length; i++) {
    partOffsets[i] = offset;
    offset += parts[i]!.length + "\n\n".length;
  }

  const anchors = fnDecls.map((f) => ({
    name: f.name,
    sourceStart: f.nameSpan.start,
    sourceLength: f.nameSpan.end - f.nameSpan.start,
    generatedStart: partOffsets[f.partIndex]! + f.prefixLength,
    generatedLength: f.name.length,
  }));

  return { code, anchors };
}
